// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://prpdjtamwfvxhzdccuxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycGRqdGFtd2Z2eGh6ZGNjdXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjA4NzQsImV4cCI6MjA2OTI5Njg3NH0.54EQghOVlTFK9cgfvewt_Mbnd8_XaEZKskCvJCjhOt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});